name: dangonewild
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  flutter_riverpod: ^2.5.1
  logger: ^2.4.0
  intl: ^0.19.0
  http: ^1.2.2
  uuid: ^4.5.0
  table_calendar: ^3.1.2
  google_places_flutter: ^2.0.9
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add this section for your assets
  assets:
    - assets/jungle_bg.png    # Replace with the actual file name you use
    - assets/                # If you want to include all files from the folder
    - assets/pine_forest_background.png
    - assets/cave_background.png
