// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnsgg9m6prYJh9xmmz31bm9Hxp2EQoemM',
    appId: '1:823785634300:android:e6e5c758d225bac22dda79',
    messagingSenderId: '823785634300',
    projectId: 'dan-gone-wild-7719d',
    storageBucket: 'dan-gone-wild-7719d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx8niakWLDz-uHJYoxcsYyGXuLMytKIkQ',
    appId: '1:823785634300:ios:0b682093a4e170492dda79',
    messagingSenderId: '823785634300',
    projectId: 'dan-gone-wild-7719d',
    storageBucket: 'dan-gone-wild-7719d.appspot.com',
    androidClientId: '823785634300-puhvfb995ihbt3s0p8go9okuhv43qldp.apps.googleusercontent.com',
    iosClientId: '823785634300-8gh7r4l6g0n5fl0tffje6j97baaaq5dl.apps.googleusercontent.com',
    iosBundleId: 'com.dangonewild.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9HcXwaCBQIp_W_62dkKfjOR4v-szYJck',
    appId: '1:823785634300:web:9f377e5f2a57dd8c2dda79',
    messagingSenderId: '823785634300',
    projectId: 'dan-gone-wild-7719d',
    authDomain: 'dan-gone-wild-7719d.firebaseapp.com',
    storageBucket: 'dan-gone-wild-7719d.appspot.com',
    measurementId: 'G-8Q584X83WT',
  );

}